LandingPageCourseCheckStatusLambdaFunctionQualifiedArn = "arn:aws:lambda:ap-southeast-1:636660820118:function:landingPageCourseCheckStatus:3"
CognitoUserPoolClientId = "466smaoga23790vpgs6r07q39b"
CognitoUserPoolId = "ap-southeast-1_gvayT1iZQ"
LandingPageCourseAccessLambdaFunctionQualifiedArn = "arn:aws:lambda:ap-southeast-1:636660820118:function:landingPageCourseAccess:2"
AuthorizationPrivateLambdaFunctionQualifiedArn = "arn:aws:lambda:ap-southeast-1:636660820118:function:authorizationPrivate:4"
HelloLambdaFunctionQualifiedArn = "arn:aws:lambda:ap-southeast-1:636660820118:function:cotai-education-dev-hello:9"
SyncContentDataTableTableName = "cotai-education-dev-cotai-education-dev-sync-content-data-table"
HttpApiId = "429hms92i2"
ServerlessDeploymentBucketName = "cotai-education-dev-deployment-bucket"
HttpApiUrl = "https://429hms92i2.execute-api.ap-southeast-1.amazonaws.com"