name: Release
on:
    push:
        branches:
            - prod

permissions:
    contents: read

jobs:
    release:
        # environment: Release
        name: Semantic Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Setup Release Dependencies
              run: pnpm add -g semantic-release@21.0.2

            - name: Setup semantic-release Dependencies
              run: pnpm add -g @semantic-release/changelog @semantic-release/git

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm exec semantic-release
